version: 0.1
input:
  google:
    calendar--events:
      summary: 'event_summary'
      start.dateTime: 'start_date_time'
      'attendees[].email': 'event_emails'
  apple-import:
    contacts:
      'fn[].value': 'full_name'
      'email[].value': 'contact_emails'
output:
  file:
    - strategy: 'csv'
      data:
        path: '/path/to/csv'
        filename: 'all_events'
        fields:
          - start_date_time
          - event_summary
          - event_emails
  obsidian:
    - strategy: 'daily_notes_append'
      data:
        date: 'start_date'
        template: |
          - ${event_summary} with [[${full_name}]] at ${start_date_time}
pipeline:
  - field: 'start_date_time'
    transform:
      - 'toStandardDate'
    toField: 'start_date'
  - field: 'start_date_time'
    transform:
      - 'toStandardTime'
    toField: 'start_time'
  - field: 'event_summary'
    transform:
      - 'trim'
  - field: 'event_emails'
    linkTo: 'contact_emails'